name: paper-maker

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      MANUSCRIPT_PATH: paper/ms # exclude the '.tex' / '.pdf' extension!
      LATEX: xelatex -shell-escape
      BIBTEX: bibtex
    steps: 
    - uses: actions/checkout@v1
    - name: Install texlive
      run: |
        sudo apt-get install texlive-publishers \
                             texlive-latex-recommended \
                             texlive-latex-extra \
                             texlive-fonts-recommended \
                             texlive-fonts-extra \
                             texlive-xetex
    - name: Build paper
      run: |
        cd ${MANUSCRIPT_PATH%/*}
        ${LATEX} ${MANUSCRIPT_PATH##*/}.tex
        ${BIBTEX} ${MANUSCRIPT_PATH##*/}.aux
        ${LATEX} ${MANUSCRIPT_PATH##*/}.tex
        ${LATEX} ${MANUSCRIPT_PATH##*/}.tex
    - name: Push paper
      run: |
        git checkout --orphan ${GITHUB_REF##*/}-pdf
        git rm -rf .github/
        cd ${MANUSCRIPT_PATH%/*}
        git rm -rf . 
        git add -f ${MANUSCRIPT_PATH##*/}.pdf
        git -c user.name='paper-maker' -c user.email='paper-maker' commit -m "update pdf"
        git push -q -f https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} ${GITHUB_REF##*/}-pdf
